config/routes.rb
Tprawngem::Application.routes.draw do
  resources :content_forms

  root :to => 'content_forms#index'

end

app/models/content_form.rb
class ContentForm < ActiveRecord::Base
  attr_accessible :content, :date, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/content_forms_controller.rb
class ContentFormsController < ApplicationController
  # GET /content_forms
  # GET /content_forms.json
  def index
    @content_forms = ContentForm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @content_forms }
    end
  end

  # GET /content_forms/1
  # GET /content_forms/1.json
  def show
    @content_form = ContentForm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.pdf do 
        pdf = ContentformPdf.new(@content_form)
        send_data(pdf.render, filename: "#{@content_form.title}.pdf",
                              type: "application/pdf",
                              disposition: "inline")
      end
      format.json { render json: @content_form }
    end
  end

  # GET /content_forms/new
  # GET /content_forms/new.json
  def new
    @content_form = ContentForm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @content_form }
    end
  end

  # GET /content_forms/1/edit
  def edit
    @content_form = ContentForm.find(params[:id])
  end

  # POST /content_forms
  # POST /content_forms.json
  def create
    @content_form = ContentForm.new(params[:content_form])

    respond_to do |format|
      if @content_form.save
        format.html { redirect_to @content_form, notice: 'Content form was successfully created.' }
        format.json { render json: @content_form, status: :created, location: @content_form }
      else
        format.html { render action: "new" }
        format.json { render json: @content_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /content_forms/1
  # PUT /content_forms/1.json
  def update
    @content_form = ContentForm.find(params[:id])

    respond_to do |format|
      if @content_form.update_attributes(params[:content_form])
        format.html { redirect_to @content_form, notice: 'Content form was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @content_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /content_forms/1
  # DELETE /content_forms/1.json
  def destroy
    @content_form = ContentForm.find(params[:id])
    @content_form.destroy

    respond_to do |format|
      format.html { redirect_to content_forms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_forms_helper.rb
module ContentFormsHelper
end

app/views/content_forms/_form.html.erb
<%= form_for(@content_form) do |f| %>
  <% if @content_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content_form.errors.count, "error") %> prohibited this content_form from being saved:</h2>

      <ul>
      <% @content_form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/content_forms/edit.html.erb
<h1>Editing content_form</h1>

<%= render 'form' %>

<%= link_to 'Show', @content_form %> |
<%= link_to 'Back', content_forms_path %>

app/views/content_forms/index.html.erb
<h1>Listing content_forms</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @content_forms.each do |content_form| %>
  <tr>
    <td><%= content_form.title %></td>
    <td><%= content_form.content %></td>
    <td><%= content_form.date %></td>
    <td><%= link_to 'Show', content_form %></td>
    <td><%= link_to 'Edit', edit_content_form_path(content_form) %></td>
    <td><%= link_to 'Destroy', content_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Content form', new_content_form_path %>

app/views/content_forms/new.html.erb
<h1>New content_form</h1>

<%= render 'form' %>

<%= link_to 'Back', content_forms_path %>

app/views/content_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @content_form.title %>
</p>

<p>
  <b>Content:</b>
  <%= @content_form.content %>
</p>

<p>
  <b>Date:</b>
  <%= @content_form.date %>
</p>


<%= link_to 'Edit', edit_content_form_path(@content_form) %> |
<%= link_to 'Back', content_forms_path %> |
<%= link_to 'Download Course Content', content_form_path(@content_form, format: "pdf") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tprawngem</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>